### ISSUE TITLE
Add Leipzig Corpus Miner to the list

### ISSUE THREAD

**Issue by eisioriginal** [dh-tech/awesome-dhtools#22]
**Item**

- [Leipzig Corpus Miner (LCM)](https://ilcm.informatik.uni-leipzig.de) - The iLCM is not a stand-alone software, but rather an infrastructure consisting of a multitude of components including a document database ([MariaDB](https://mariadb.org/)), an NLP pipeline for processing different text mining processes ([In R statistical language](https://mran.microsoft.com/open)), a full-text index ([Solr](http://lucene.apache.org/solr/)) and a web application ([R Shiny](https://shiny.rstudio.com/)). To make the infrastructure available as a decentralized installation for other projects it is embedded in a virtual machine ensemble ([Docker](https://www.docker.com/)), which can be easily set up with predefined configuration scripts. The application is therefor a fusion of R scripting capabilities, Data Management and visualization by R Shiny.

**Rationale for the change**

I think this tool is very useful for the community. I'm one of the authors and want to contribute the tool to a broader audience. We had some publications on the tool and right now we are starting to create a constant support structure. More users would allow us to learn and cooperate with many more scholars.

Please note that this project is released with a
[Contributor Code of Conduct](CODE_OF_CONDUCT.md). By participating in this
project you agree to abide by its terms.

**Comment by maehr** [comment]
Hi @eisioriginal
Thanks a lot. I like your pitch and the software you are building.  Are you planning on open sourcing it? When will you release an updated documentation?
Cheers
Moritz
Ps: You can add the item to the readme file and open a pull request.

**Comment by eisioriginal** [comment]
Dear @maehr ,
yes we will release it as open source. Actually it is open source, but the images are very big. So we are thinking at the moment how best to get distribution and source code across. The sources will be provided by the University of Leipzig. There are no plans that we will not release anything transparently. 

The documentation will be done in the style of a GitHib page with the next funding, which is going on right now. But there is a First Steps PDF, which is quite ok for a start. But we are aware that this is not enough.

All the best

Andreas

Can I just clone the project and create a branch/pull request or do I need some rights?

**Comment by eisioriginal** [comment]
@maehr Am I missing something? I pulled the project; created a branch and wanted to push the branch back. Result is:

git.exe push --progress "origin" add_corpus_miner:add_corpus_miner
remote: Permission to dh-tech/awesome-dhtools.git denied to eisioriginal.
fatal: unable to access 'https://github.com/dh-tech/awesome-dhtools.git/': The requested URL returned error: 403

Am I missing something here? Sorry I havn't contributed to GitHub projects for a long time.

**Comment by maehr** [comment]
Thank you @eisioriginal Your PR https://github.com/dh-tech/awesome-dhtools/pull/23 has been merged. The issue has therefore been closed.
